export enum BullProcesses {
  SEND_VERIFICATION_EMAIL = 'SEND_VERIFICATION_EMAIL',
  SEND_PASSWORD_RESET_EMAIL = 'SEND_PASSWORD_RESET_EMAIL',
  SEND_VERIFICATION_SMS = 'SEND_VERIFICATION_SMS',
  GENERATE_TOLL_DISTANCES = 'GENERATE_TOLL_DISTANCES',
}
