import { registerEnumType } from '@nestjs/graphql';

export enum TokenErrors {
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  REFRESH_TOKEN_NOT_PROVIDED = 'REFRESH_TOKEN_NOT_PROVIDED',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  ACCESS_TOKEN_NOT_PROVIDED = 'ACCESS_TOKEN_NOT_PROVIDED',
  INVALID_ACCESS_TOKEN = 'INVALID_ACCESS_TOKEN',
  INVALID_GOOGLE_OAUTH_TOKEN = 'INVALID_GOOGLE_OAUTH_TOKEN',
}
registerEnumType(TokenErrors, {
  name: 'TokenErrors',
});
