services:
  gateway:
    build:
      dockerfile: development.Dockerfile
      args:
        - SERVICE_NAME=gateway
    volumes:
      - ./services:/usr/src/app/services
      - ./lib:/usr/src/app/lib
    ports:
      - 3000:3000

  auth:
    build:
      dockerfile: development.Dockerfile
      args:
        - SERVICE_NAME=auth
    volumes:
      - ./services:/usr/src/app/services
      - ./lib:/usr/src/app/lib
    ports:
      - 3001:3001

  postgres:
    image: postgres
    env_file:
      - postgres.env
    environment:
      POSTGRES_DB: peagepay
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    restart: always
    ports:
      - 5000:8080

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
