import { registerEnumType } from '@nestjs/graphql';

export enum AuthErrors {
  USER_WITH_EMAIL_EXISTS = 'USER_WITH_EMAIL_EXISTS',
  USER_WITH_PHONE_EXISTS = 'USER_WITH_PHONE_EXISTS',
  VERIFICATION_TOKEN_NOT_FOUND = 'VERIFICATION_TOKEN_NOT_FOUND',
  EMAIL_AUTH_NOT_FOUND = 'EMAIL_AUTH_NOT_FOUND',
  PHONE_AUTH_NOT_FOUND = 'PHONE_AUTH_NOT_FOUND',
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  VERIFICATION_TOKEN_EXPIRED = 'VERIFICATION_TOKEN_EXPIRED',
  INVALID_VERIFICATION_TOKEN = 'INVALID_VERIFICATION_TOKEN',
  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
}
registerEnumType(AuthErrors, {
  name: 'AuthErrors',
});
