import { registerEnumType } from '@nestjs/graphql';

export enum AuthErrors {
  EMAIL_ALREADY_VERIFIED = 'EMAIL_ALREADY_VERIFIED',
  INVALID_EMAIL_OR_PASSWORD = 'INVALID_EMAIL_OR_PASSWORD',
  VERIFICATION_REQUEST_PENDING = 'VERIFICATION_REQUEST_PENDING',
  SIGN_IN_WITH_EMAIl_ATTEMPTS_EXCEEDED = 'SIGN_IN_WITH_EMAIl_ATTEMPTS_EXCEEDED',
  EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED = 'EMAIL_VERIFICATION_ATTEMPTS_EXCEEDED',
  PASSWORD_RESET_ATTEMPTS_EXCEEDED = 'PASSWORD_RESET_ATTEMPTS_EXCEEDED',
  INVALID_PIN = 'INVALID_PIN',
}
registerEnumType(AuthErrors, {
  name: 'AuthErrors',
});
